version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5402:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: milieuthemas

  web:
    build: ./web
    ports:
      - "8101:8000"
    links:
      - database
    volumes:
      - $PWD/reports:/app/reports
    environment:
      - SECRET_KEY=insecure
      - DB_NAME=milieuthemas
      - DB_PASSWORD=insecure
      - CONSUL_HOST=${CONSUL_HOST:-notset}
      - CONSUL_PORT=${CONSUL_PORT:-8500}
