version: '3.0'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5402:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: milieuthemas

  web:
    build: ./web
    ports:
      - "8101:8000"
    links:
      - database
    volumes:
      - $PWD/reports:/app/reports
    environment:
      - DATAPUNT_API_URL=${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      - SECRET_KEY=insecure
      - DATABASE_NAME=milieuthemas
      - DATABASE_PASSWORD=insecure
      - UWSGI_HTTP=":8000"
      - UWSGI_MODULE="milieuthemas.wsgi:application"
      - UWSGI_MASTER=1
      - UWSGI_STATIC_MAP="/static=/static"
      - UWSGI_PROCESSES=4

