version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: milieuthemas

  tests:
    build: ../web
    links:
      - database
    command: >
      bash -c "/app/docker-wait.sh \
              && python manage.py test"
