version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: milieuthemas

  importer:
    image: ${DOCKER_REGISTRY_HOST}/datapunt/milieuthemas:${ENVIRONMENT}
    links:
      - database
    environment:
      MILIEUTHEMAS_OBJECTSTORE_PASSWORD:
      DATABASE_NAME: milieuthemas
      DATABASE_USER: milieuthemas
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
    command: >
      bash -c "/app/docker-wait.sh \
              && python get_import_data.py \
              && python manage.py migrate \
              && python manage.py sync_views \
              && python manage.py run_import "

  db-backup:
    image: amsterdam/postgres11
    links:
      - database
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo database:5432:milieuthemas:milieuthemas:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump \
                --clean \
                -Fc \
                -U milieuthemas \
                -h database -p 5432 \
                milieuthemas > /tmp/backups/database.dump"
