# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 08:15
# Python
from __future__ import unicode_literals
# Packages
from django.db import migrations
# Project
from geo_views import migrate

class Migration(migrations.Migration):

    dependencies = [
        ('geo_views', '0003_schiphol_vogel'),
    ]

    operations = [
        migrate.ManageView(
            view_name="geo_risicozones_bedrijven_bron",
            sql="""SELECT id, bedrijfsnaam AS display, hoeveelheid_stof, type_stof,
                    geometrie_polygon AS geometrie
                    FROM risicozones_bedrijven_bron
                    WHERE geometrie_polygon IS NOT NULL"""
        ),
        migrate.ManageView(
            view_name="geo_risicozones_bedrijven_bedrijf",
            sql="""SELECT id, bedrijfsnaam as display, bevoegd_gezag, categorie_bevi,
                    type_bedrijf, geometrie_polygon AS geometrie
                    FROM risicozones_bedrijven_bedrijf
                    WHERE geometrie_polygon IS NOT NULL"""
        ),
        
    ]
