# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 19:46
from __future__ import unicode_literals

from django.db import migrations
from geo_views import migrate


class Migration(migrations.Migration):

    dependencies = [
        ('geo_views', '0008_risicozones_infrastructuur'),
        ('geluidzone', '0001_initial'),
    ]

    operations = [
        migrate.ManageView(
            view_name="geo_geluidzone_spoorwegen",
            sql="""SELECT id, geo_id, geometrie
                    FROM geluidzone_spoorwegen
                    WHERE geometrie IS NOT NULL"""
        ),
        migrate.ManageView(
            view_name="geo_geluidzone_metro",
            sql="""SELECT id, geo_id, geometrie
                    FROM geluidzone_metro
                    WHERE geometrie IS NOT NULL"""
        ),
        migrate.ManageView(
            view_name="geo_geluidzone_industrie",
            sql="""SELECT id, geo_id, geometrie, naam AS display, type
                    FROM geluidzone_industrie
                    WHERE geometrie IS NOT NULL"""
        ),
    ]
