# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 08:05
from __future__ import unicode_literals

from django.db import migrations
from geo_views import migrate

class Migration(migrations.Migration):

    dependencies = [
        ('geo_views', '0009_geluidzones'),
    ]

    operations = [
        migrate.ManageView(
            view_name="geo_risicozones_infrastructuur_aardgasgebied_100let",
            sql="""SELECT id, geometrie
                    FROM risicozones_infrastructuur_aardgasgebied
                    WHERE geometrie IS NOT NULL AND type='la'"""
        ),
        migrate.ManageView(
            view_name="geo_risicozones_infrastructuur_aardgasgebied_1let",
            sql="""SELECT id, geometrie
                    FROM risicozones_infrastructuur_aardgasgebied
                    WHERE geometrie IS NOT NULL AND type='l1'"""
        ),
        migrate.ManageView(
            view_name="geo_risicozones_infrastructuur_aardgasgebied_zakelijk",
            sql="""SELECT id, geometrie
                    FROM risicozones_infrastructuur_aardgasgebied
                    WHERE geometrie IS NOT NULL AND type='zk'"""
        ),
        migrate.ManageView(
            view_name="geo_risicozones_infrastructuur_aardgasgebied_plaatsgebonden_risico",
            sql="""SELECT id, geometrie
                    FROM risicozones_infrastructuur_aardgasgebied
                    WHERE geometrie IS NOT NULL AND type='pr'"""
        ),
        migrate.ManageView(
            view_name="geo_risicozones_infrastructuur_aardgasleidingen",
            sql="""SELECT id, geometrie
                    FROM risicozones_infrastructuur_aardgasleiding
                    WHERE geometrie IS NOT NULL"""
        ),
    ]
