version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: milieuthemas

  tests:
    build: ../web
    links:
      - database
    command: >
      bash -c "/app/docker-wait.sh \
              && python manage.py test"

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/milieuthemas:${ENVIRONMENT}
    links:
      - database
    environment:
      MILIEUTHEMAS_OBJECTSTORE_PASSWORD:
      DB_NAME: milieuthemas
      DB_USER: milieuthemas
      DB_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
    command: >
      bash -c "/app/docker-wait.sh \
              && python get_import_data.py \
              && python manage.py migrate \
              && python manage.py sync_views \
              && python manage.py run_import "

  db-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    links:
      - database
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo database:5432:milieuthemas:milieuthemas:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump --clean \
                          -Fc \
                          -t bodeminformatie* \
                          -t geluidzone* \
                          -t risicozones* \
                          -t schiphol* \
                          -t themas* \
                          -t veiligheidsafstanden* \
                          -t bommenkaart* \
                          -t geo* \
                          -t django_migrations  \
                          -t django_site \
                          -T auth*    \
                          -U milieuthemas \
                          -h database -p 5432 \
                          milieuthemas > /tmp/backups/database.dump"
