from django.conf.urls import url, include
from rest_framework import renderers, schemas, response
from rest_framework.decorators import api_view, renderer_classes
from rest_framework_swagger.renderers import OpenAPIRenderer
from rest_framework_swagger.renderers import SwaggerUIRenderer


@api_view()
@renderer_classes(
    [SwaggerUIRenderer, OpenAPIRenderer, renderers.CoreJSONRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(
        title='Milieuthemas API does not exist :)',
    )
    return response.Response(generator.get_schema(request=request))

# we only create some geoviews.

urlpatterns = [
    # Initial autogenerated schema
    # url(r'^docs/swagger/$', schema_view),
    url(r'^milieuthemas/', include('atlas_api.urls'), name="homepage"),
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^status/',
        include('datapunt_generic.health.urls', namespace='health')),
]
