from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import renderers, schemas, response
from rest_framework.decorators import api_view, renderer_classes
from rest_framework_swagger.renderers import OpenAPIRenderer
from rest_framework_swagger.renderers import SwaggerUIRenderer

import datapunt_generic.batch.views as b_views


@api_view()
@renderer_classes(
    [SwaggerUIRenderer, OpenAPIRenderer, renderers.CoreJSONRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(
        title='BAG API',

    )
    return response.Response(generator.get_schema(request=request))


urlpatterns = [
    # Initial autogenerated schema
    url('^docs/swagger/$', schema_view),
    url(r'^milieuthemas/', include('atlas_api.urls'), name="homepage"),
    url(r'^jobs/?$', b_views.JobListView.as_view(), name='job-list'),
    url(r'^jobs/(?P<pk>.*)$', b_views.JobDetailView.as_view(),
        name='job-detail'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^status/',
        include('datapunt_generic.health.urls', namespace='health')),
]
